/**
 * @see {@link https://github.com/Steellgold/supa-clicker/blob/c6c339e2b3ebc561277bae90f77a90e36d87b945/lib/constants/special-items.ts}
 */
export const SPECIAL_ITEM_IDS = {
  // Features & Unlocks
  STACK_OVERFLOW: 21,

  // Upgrade Boosts
  AI_TRAINING_PLUS: 2,
  DEV_CERTIFICATION: 3,
  KUBERNETES_MASTER: 4,
  CLOUD_CERTIFICATION: 5,
  ML_EXPERTISE: 6,

  // Global Multipliers
  SUPABASE_PRO: 7,
  ENTERPRISE_PLAN: 8,
  UNICORN_STATUS: 9,
  IPO: 10,
  TECH_MONOPOLY: 11,
  CAFFEINE_IV: 23,

  // Special Click Effects
  GOLDEN_CLICK: 12,
  LUCKY_STREAK: 13,
  COMBO_MASTER: 14,
  TIME_WARP: 15,
  FRENZY_MODE: 16,

  // Automation
  AUTO_CLICKER: 17,
  TURBO_AUTO_CLICKER: 18,
  HYPER_AUTO_CLICKER: 19,
  QUANTUM_AUTO_CLICKER: 20,

  // Fun/Meme Items
  DUCK_WALKER: 22,
} as const;

export const SPECIAL_ITEM_EFFECTS = {
  // Upgrade Boosts
  AI_INTERN_BOOST: "x2 AI Intern",
  JUNIOR_DEV_BOOST: "x3 Junior Dev",
  DEVOPS_BOOST: "x2 DevOps",
  CLOUD_BOOST: "x1.5 Cloud",
  AI_ML_BOOST: "x3 AI/ML",

  // Global Effects
  GLOBAL_1_5X: "x1.5 Global",
  GLOBAL_2X: "x2 Global",
  GLOBAL_3X: "x3 Global",
  GLOBAL_5X: "x5 Global",
  GLOBAL_10X: "x10 Global",

  // Special Effects
  GOLDEN_CLICK: "Golden Click",
  LUCKY_STREAK: "Lucky Streak",
  COMBO_SYSTEM: "Combo Master",
  TIME_BOOST: "Time Warp",
  CLICK_FRENZY: "Frenzy Mode",

  // Automation Effects
  AUTO_CLICK: "Auto-Clicker",
  TURBO_AUTO: "Turbo Auto-Clicker",
  HYPER_AUTO: "Hyper Auto-Clicker",
  QUANTUM_AUTO: "Quantum Auto-Clicker",

  // Feature Unlocks
  DEBUG_MODE: "Debug Mode",
  DUCK_WALKER: "Duck Walker",
  CAFFEINE_BOOST: "Caffeine Boost",
} as const;

export const SPECIAL_ITEM_CATEGORIES = {
  UPGRADE_BOOST: "upgrade_boost",
  GLOBAL: "global",
  SPECIAL: "special",
  AUTOMATION: "automation",
} as const;

/**
 * @see {@link https://github.com/Steellgold/supa-clicker/blob/hackathon/lib/upgrades-specials.ts}
 */
export const SPECIAL_ITEMS = [
  {
    id: SPECIAL_ITEM_IDS.AI_TRAINING_PLUS,
    name: "AI Training+",
    description: "Double the efficiency of AI Interns",
    baseCost: 1000,
    costGrowth: 2.0,
    effect: SPECIAL_ITEM_EFFECTS.AI_INTERN_BOOST,
    multiplier: 2,
    category: SPECIAL_ITEM_CATEGORIES.UPGRADE_BOOST,
    unlockRequirement: 500,
    maxPurchases: 1,
    isFeatureUnlock: true,
  },
  {
    id: SPECIAL_ITEM_IDS.DEV_CERTIFICATION,
    name: "Dev Certification",
    description: "Triple the efficiency of Junior Devs",
    baseCost: 5000,
    costGrowth: 2.0,
    effect: SPECIAL_ITEM_EFFECTS.JUNIOR_DEV_BOOST,
    multiplier: 3,
    category: SPECIAL_ITEM_CATEGORIES.UPGRADE_BOOST,
    unlockRequirement: 1000,
    maxPurchases: 1,
  },
  {
    id: SPECIAL_ITEM_IDS.KUBERNETES_MASTER,
    name: "Kubernetes Master",
    description: "Double the efficiency of DevOps",
    baseCost: 15000,
    costGrowth: 2.0,
    effect: SPECIAL_ITEM_EFFECTS.DEVOPS_BOOST,
    multiplier: 2,
    category: SPECIAL_ITEM_CATEGORIES.UPGRADE_BOOST,
    unlockRequirement: 2000,
  },
  {
    id: SPECIAL_ITEM_IDS.CLOUD_CERTIFICATION,
    name: "Cloud Certification",
    description: "x1.5 all cloud upgrades",
    baseCost: 50000,
    costGrowth: 2.0,
    effect: SPECIAL_ITEM_EFFECTS.CLOUD_BOOST,
    multiplier: 1.5,
    category: SPECIAL_ITEM_CATEGORIES.UPGRADE_BOOST,
    unlockRequirement: 3000,
  },
  {
    id: SPECIAL_ITEM_IDS.ML_EXPERTISE,
    name: "ML Expertise",
    description: "x3 all AI/ML upgrades",
    baseCost: 200000,
    costGrowth: 2.0,
    effect: SPECIAL_ITEM_EFFECTS.AI_ML_BOOST,
    multiplier: 3,
    category: SPECIAL_ITEM_CATEGORIES.UPGRADE_BOOST,
    unlockRequirement: 5000,
    maxPurchases: 2,
  },

  // Global Multipliers - Tier 1
  {
    id: SPECIAL_ITEM_IDS.SUPABASE_PRO,
    name: "Supabase Pro",
    description: "Multiply all gains by 1.5",
    baseCost: 100000,
    costGrowth: 3.0,
    effect: SPECIAL_ITEM_EFFECTS.GLOBAL_1_5X,
    multiplier: 1.5,
    category: SPECIAL_ITEM_CATEGORIES.GLOBAL,
    unlockRequirement: 2500,
    maxPurchases: 2,
  },
  {
    id: SPECIAL_ITEM_IDS.ENTERPRISE_PLAN,
    name: "Enterprise Plan",
    description: "Multiply all gains by 2",
    baseCost: 500000,
    costGrowth: 3.0,
    effect: SPECIAL_ITEM_EFFECTS.GLOBAL_2X,
    multiplier: 2,
    category: SPECIAL_ITEM_CATEGORIES.GLOBAL,
    unlockRequirement: 5000,
    maxPurchases: 2,
  },
  {
    id: SPECIAL_ITEM_IDS.UNICORN_STATUS,
    name: "Unicorn Status",
    description: "Multiply all gains by 3",
    baseCost: 2000000,
    costGrowth: 3.0,
    effect: SPECIAL_ITEM_EFFECTS.GLOBAL_3X,
    multiplier: 3,
    category: SPECIAL_ITEM_CATEGORIES.GLOBAL,
    unlockRequirement: 10000,
    maxPurchases: 2,
  },
  {
    id: SPECIAL_ITEM_IDS.IPO,
    name: "IPO",
    description: "Multiply all gains by 5",
    baseCost: 10000000,
    costGrowth: 3.0,
    effect: SPECIAL_ITEM_EFFECTS.GLOBAL_5X,
    multiplier: 5,
    category: SPECIAL_ITEM_CATEGORIES.GLOBAL,
    unlockRequirement: 25000,
    maxPurchases: 1,
  },
  {
    id: SPECIAL_ITEM_IDS.TECH_MONOPOLY,
    name: "Tech Monopoly",
    description: "Multiply all gains by 10",
    baseCost: 1000000000,
    costGrowth: 100,
    effect: SPECIAL_ITEM_EFFECTS.GLOBAL_10X,
    multiplier: 10,
    category: SPECIAL_ITEM_CATEGORIES.GLOBAL,
    unlockRequirement: 50000,
    maxPurchases: 1,
  },

  // Special Effects - Tier 1
  {
    id: SPECIAL_ITEM_IDS.GOLDEN_CLICK,
    name: "Golden Click",
    description: "1% chance for click x100",
    baseCost: 25000,
    costGrowth: 2.5,
    effect: SPECIAL_ITEM_EFFECTS.GOLDEN_CLICK,
    multiplier: 1,
    category: SPECIAL_ITEM_CATEGORIES.SPECIAL,
    unlockRequirement: 3000,
    maxPurchases: 100,
  },
  {
    id: SPECIAL_ITEM_IDS.LUCKY_STREAK,
    name: "Lucky Streak",
    description: "2% chance for click x50",
    baseCost: 75000,
    costGrowth: 2.5,
    effect: SPECIAL_ITEM_EFFECTS.LUCKY_STREAK,
    multiplier: 1,
    category: SPECIAL_ITEM_CATEGORIES.SPECIAL,
    unlockRequirement: 5000,
    maxPurchases: 50,
  },
  {
    id: SPECIAL_ITEM_IDS.COMBO_MASTER,
    name: "Combo Master",
    description: "Fast clicks = bonus",
    baseCost: 150000,
    costGrowth: 2.5,
    effect: SPECIAL_ITEM_EFFECTS.COMBO_SYSTEM,
    multiplier: 1,
    category: SPECIAL_ITEM_CATEGORIES.SPECIAL,
    unlockRequirement: 7500,
  },
  // {
  //   id: SPECIAL_ITEM_IDS.TIME_WARP,
  //   name: "Time Warp",
  //   description: "10s of production x2",
  //   baseCost: 300000,
  //   costGrowth: 2.5,
  //   effect: SPECIAL_ITEM_EFFECTS.TIME_BOOST,
  //   multiplier: 1,
  //   category: SPECIAL_ITEM_CATEGORIES.SPECIAL,
  //   unlockRequirement: 10000,
  // },
  // {
  //   id: SPECIAL_ITEM_IDS.FRENZY_MODE,
  //   name: "Frenzy Mode",
  //   description: "30s of clicks x5",
  //   baseCost: 600000,
  //   costGrowth: 2.5,
  //   effect: SPECIAL_ITEM_EFFECTS.CLICK_FRENZY,
  //   multiplier: 1,
  //   category: SPECIAL_ITEM_CATEGORIES.SPECIAL,
  //   unlockRequirement: 15000,
  // },

  // Automation - Tier 1
  {
    id: SPECIAL_ITEM_IDS.AUTO_CLICKER,
    name: "Auto-Clicker",
    description: "1 automatic click per second",
    baseCost: 50000,
    costGrowth: 2.2,
    effect: SPECIAL_ITEM_EFFECTS.AUTO_CLICK,
    multiplier: 1,
    category: SPECIAL_ITEM_CATEGORIES.AUTOMATION,
    unlockRequirement: 4000,
  },
  {
    id: SPECIAL_ITEM_IDS.TURBO_AUTO_CLICKER,
    name: "Turbo Auto-Clicker",
    description: "5 automatic clicks per second",
    baseCost: 250000,
    costGrowth: 2.2,
    effect: SPECIAL_ITEM_EFFECTS.TURBO_AUTO,
    multiplier: 5,
    category: SPECIAL_ITEM_CATEGORIES.AUTOMATION,
    unlockRequirement: 8000,
  },
  {
    id: SPECIAL_ITEM_IDS.HYPER_AUTO_CLICKER,
    name: "Hyper Auto-Clicker",
    description: "10 automatic clicks per second",
    baseCost: 1000000,
    costGrowth: 2.2,
    effect: SPECIAL_ITEM_EFFECTS.HYPER_AUTO,
    multiplier: 10,
    category: SPECIAL_ITEM_CATEGORIES.AUTOMATION,
    unlockRequirement: 15000,
    maxPurchases: 5,
  },
  {
    id: SPECIAL_ITEM_IDS.QUANTUM_AUTO_CLICKER,
    name: "Quantum Auto-Clicker",
    description: "25 automatic clicks per second",
    baseCost: 5000000,
    costGrowth: 2.2,
    effect: SPECIAL_ITEM_EFFECTS.QUANTUM_AUTO,
    multiplier: 25,
    category: SPECIAL_ITEM_CATEGORIES.AUTOMATION,
    unlockRequirement: 30000,
    maxPurchases: 3,
  },

  // Fun/Meme Items (easier to get early)
  // {
  //   id: SPECIAL_ITEM_IDS.STACK_OVERFLOW,
  //   name: "Stack Overflow",
  //   description: "Instantly solve all bugs",
  //   baseCost: 2500,
  //   costGrowth: 2.0,
  //   effect: SPECIAL_ITEM_EFFECTS.DEBUG_MODE,
  //   multiplier: 1,
  //   category: SPECIAL_ITEM_CATEGORIES.SPECIAL,
  //   unlockRequirement: 1000,
  //   maxPurchases: 1,
  //   isFeatureUnlock: true,
  // },
  {
    id: SPECIAL_ITEM_IDS.DUCK_WALKER,
    name: "Duck Walker",
    description: "Animated ducks walk across the screen - click them for bonus power!",
    baseCost: 5000,
    costGrowth: 2.0,
    effect: SPECIAL_ITEM_EFFECTS.DUCK_WALKER,
    multiplier: 1,
    category: SPECIAL_ITEM_CATEGORIES.SPECIAL,
    unlockRequirement: 1500,
  },
  {
    id: SPECIAL_ITEM_IDS.CAFFEINE_IV,
    name: "Caffeine IV",
    description: "Caffeine drip to code 24/7",
    baseCost: 10000,
    costGrowth: 2.0,
    effect: SPECIAL_ITEM_EFFECTS.CAFFEINE_BOOST,
    multiplier: 1.2,
    category: SPECIAL_ITEM_CATEGORIES.GLOBAL,
    unlockRequirement: 2000,
    maxPurchases: 2,
  },
];
